#!/bin/bash

color="#e5e5e5"
volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -oP '(yes|no)')

if [[ $mute == "yes" ]]; then
    echo "<span foreground='$color'>Vol</span> muted"
else
    echo "<span foreground='$color'>Vol</span> $volume"
fi

