#!/bin/sh

alpha='dd'
background='#1a1b26'
foreground='#a9b1d6'
selection='#1a1b26'
comment='#9ece6a'

yellow='#e0af68'
orange='#ffb86c'
red='#f7768e'
magenta='#ad8ee6'
blue='#4d6a8e'
cyan='#449dab'
green='#9ece6a'
white='#a9b1d6'
i3lock \
  --insidever-color=$selection$alpha \
  --insidewrong-color=$selection$alpha \
  --inside-color=$selection$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$blue$alpha \
  --line-uses-ring \
  --keyhl-color=$green$alpha \
  --bshl-color=$yellow$alpha \
  --separator-color=$selection$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --modif-color=$red \
  --layout-color=$blue \
  --date-color=$foreground \
  --time-color=$foreground \
  --screen 1 \
  --blur 1 \
  --clock \
  --indicator \
  --time-str="%l:%M %p" \
  --date-str="%A %e %B %Y" \
  --verif-text="Checking..." \
  --wrong-text="Wrong pswd" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --radius=120 \
  --ring-width=10 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
 # --time-font="JetBrainsMono Nerd Font" \
# --date-font="JetBrainsMono Nerd Font " \
#  --layout-font="JetBrainsMono Nerd Font" \
#  --verif-font="JetBrainsMono Nerd Font" \
#  --wrong-font="JetBrainsMono Nerd Font" \

# These last five lines are commented because they concern the font you want to use.
# JetBrainsMono Nerd Font is the font that was used in the screenshot.
# To specify a favorite font, just uncomment the five lines and replace the parameter with the font you prefer.
