#!/bin/sh

# Power menu with customized W-Menu using your new settings
choice=$(printf "Shutdown\nReboot\nSuspend\nLogout" | wmenu \
    -p "Power Menu:" \
    -f "JetBrainsMono Nerd Font 13.5" \
    -l 4 \
    -N 272E33 \
    -n d3c6aa \
    -M 6F9B7E \
    -m 272E33 \
    -S 6F9B7E \
    -s 272E33
)

case $choice in
    "Reboot")
        confirm=$(printf "Yes\nNo" | wmenu \
            -p "Reboot - Are you sure?" \
            -f "JetBrainsMono Nerd Font 13.5" \
            -l 2 \
            -N 272E33 \
            -n d3c6aa \
            -M 6F9B7E \
            -m 272E33 \
            -S 6F9B7E \
            -s 272E33
        )
        if [ "$confirm" = "Yes" ]; then
            systemctl reboot
        fi
        ;;
    "Shutdown")
        confirm=$(printf "Yes\nNo" | wmenu \
            -p "Shutdown - Are you sure?" \
            -f "JetBrainsMono Nerd Font 13.5" \
            -l 2 \
            -N 272E33 \
            -n d3c6aa \
            -M 6F9B7E \
            -m 272E33 \
            -S 6F9B7E \
            -s 272E33
        )
        if [ "$confirm" = "Yes" ]; then
            systemctl poweroff
        fi
        ;;
    "Suspend")
        confirm=$(printf "Yes\nNo" | wmenu \
            -p "Suspend - Are you sure?" \
            -f "JetBrainsMono Nerd Font 13.5" \
            -l 2 \
            -N 272E33 \
            -n d3c6aa \
            -M 6F9B7E \
            -m 272E33 \
            -S 6F9B7E \
            -s 272E33
        )
        if [ "$confirm" = "Yes" ]; then
            systemctl suspend
        fi
        ;;
    "Logout")
        confirm=$(printf "Yes\nNo" | wmenu \
            -p "Logout - Are you sure?" \
            -f "JetBrainsMono Nerd Font 13.5" \
            -l 2 \
            -N 272E33 \
            -n d3c6aa \
            -M 6F9B7E \
            -m 272E33 \
            -S 6F9B7E \
            -s 272E33
        )
        if [ "$confirm" = "Yes" ]; then
            pkill -KILL -u "$USER"
        fi
        ;;
esac

