#!/bin/bash

export DISPLAY=:0
export XAUTHORITY="/home/zaid/.Xauthority"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

choice=$(echo -e "  Shutdown\n  Reboot\n󰤄  Suspend\n󰍃  Logout" | rofi -dmenu -i -p "Power Menu")

case "$choice" in
  *Shutdown*) sudo poweroff ;;
  *Reboot*) sudo reboot ;;
  *Suspend*) sudo zzz ;;
  *Logout*) i3-msg exit ;;
esac

# to make this script work you need to add this command by type it in your terminal: (dont missing replace the zaid with your username!!)

#echo "zaid ALL=(ALL) NOPASSWD: /sbin/poweroff, /sbin/reboot, /usr/sbin/zzz" | sudo EDITOR='tee -a' visudo

# this command for make the three commands " poweroff , reboot, zzz," running without the passowrd sudo.

