#!/bin/bash

export DISPLAY=:0
export XAUTHORITY="/home/zaid/.Xauthority"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

confirm() {
    rofi -dmenu -p "Are you sure? [Y/N]" <<< "" | grep -iq "^y"
}

choice=$(printf "<span foreground='#e06c75'></span> Shutdown\n<span foreground='#61afef'></span> Reboot\n<span foreground='#98c379'>󰤄</span> Suspend\n<span foreground='#e5c07b'>󰍃</span> Logout" | rofi -dmenu -i -markup-rows -p "󰤆 Power Menu:")

case "$choice" in
  *Shutdown*)
    confirm && sudo poweroff
    ;;
  *Reboot*)
    confirm && sudo reboot
    ;;
  *Suspend*)
    confirm && sudo zzz
    ;;
  *Logout*)
    confirm && i3-msg exit
    ;;
esac

# to make this script work you need to add this command by type it in your terminal: (dont missing replace the zaid with your username!!)

#echo "zaid ALL=(ALL) NOPASSWD: /sbin/poweroff, /sbin/reboot, /usr/sbin/zzz" | sudo EDITOR='tee -a' visudo

# this command for make the three commands " poweroff , reboot, zzz," running without the passowrd sudo.

