#!/bin/bash

color="#a9b1d6"

mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')

mem_used=$((mem_total - mem_available))

mem_total_g=$(awk "BEGIN {printf \"%.0f\", $mem_total/1024/1024}")

if [ $mem_used -lt 1048576 ]; then
    mem_used_m=$(awk "BEGIN {printf \"%.0f\", $mem_used/1024}")
    echo "<span foreground='$color'>Ram</span> ${mem_used_m}M/${mem_total_g}G"
else
    mem_used_g=$(awk "BEGIN {printf \"%.1f\", $mem_used/1024/1024}")
    echo "<span foreground='$color'>Ram</span> ${mem_used_g}G/${mem_total_g}G"
fi

