#!/bin/sh

color="#d3c6aa"

status=$(amixer get 'Capture' | grep '\[on\]')

if [ -n "$status" ]; then
    echo "<span foreground='$color'>Mic</span> on"
else
    echo "<span foreground='$color'>Mic</span> muted"
fi

