#!/bin/sh

profile=$(powerprofilesctl get)

case "$profile" in
    performance)
        echo "(perf)"
        ;;
    balanced)
        echo "(balnc)"
        ;;
    power-saver)
        echo "(saver)"
        ;;
    *)
        echo "(unknown)"
        ;;
esac

