#!/bin/bash

color="#a9b1d6"

wifi_iface=$(ip link show | awk -F: '/wl/ {gsub(/ /,"",$2); print $2; exit}')

if [[ -z "$wifi_iface" ]]; then
    echo "<span foreground='$color'>Wifi</span> down"
    exit 0
fi

state=$(cat /sys/class/net/"$wifi_iface"/operstate 2>/dev/null)

if [[ "$state" == "up" ]]; then
    echo "<span foreground='$color'>Wifi</span> up"
else
    echo "<span foreground='$color'>Wifi</span> down"
fi

