# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34' # or #282c34
foreground = '#bbc2cf'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
# orange  = '#d19a66'
blue    = '#61afef' # and #2577B8 for i3 and rofi or #3D8EC9
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
