#!/bin/bash

color="#7aa2f7"

BRIGHTNESS_PATH="/sys/class/backlight/intel_backlight"

current=$(cat "$BRIGHTNESS_PATH/brightness")
max=$(cat "$BRIGHTNESS_PATH/max_brightness")

percent=$(( 100 * current / max ))

echo "<span foreground='$color'>Bri</span> $percent%"

