#!/bin/bash

prev_idle=$(grep 'cpu ' /proc/stat | awk '{print $5}')
prev_total=$(grep 'cpu ' /proc/stat | awk '{total=0; for (i=2;i<=NF;i++) total+=$i; print total}')
sleep 1
idle=$(grep 'cpu ' /proc/stat | awk '{print $5}')
total=$(grep 'cpu ' /proc/stat | awk '{total=0; for (i=2;i<=NF;i++) total+=$i; print total}')

diff_idle=$((idle - prev_idle))
diff_total=$((total - prev_total))
usage=$(( (100 * (diff_total - diff_idle)) / diff_total ))
temp=$(sensors | grep -m 1 'Package id 0' | awk '{print $4}' | tr -d '+')

echo "<span color='#719cd6'> </span>$usage%-$temp"
