#!/bin/bash

color="#7aa2f7"

iface=$(ip -o link show | awk -F': ' '/ether/ {print $2}' | grep -E '^(en|eth|eno|ens|enp)' | head -n1) || exit 1

state=$(cat /sys/class/net/"$iface"/operstate 2>/dev/null) || state="down"

if [[ "$state" == "up" ]]; then
    echo "<span foreground='$color'>Eth</span> up"
else
    echo "<span foreground='$color'>Eth</span> down"
fi

