#!/bin/bash

layout=$(xkb-switch)

case "$layout" in
    us)
        echo "<span color='#baa1e2'> </span>US"
        ;;
    ara)
        echo "<span color='#baa1e2'> </span>AR"
        ;;
    *)
        echo "$layout"
        echo "$layout"
        ;;
esac

