#!/bin/bash

layout=$(xkb-switch)

case "$layout" in
    us)
        echo "<span color='#c397d8'> </span>us"
        ;;
    ara)
        echo "<span color='#c397d8'> </span>ar"
        ;;
    *)
        echo "$layout"
        echo "$layout"
        ;;
esac

