#!/bin/bash

layout=$(xkb-switch)

case "$layout" in
    us)
        echo "[US]"
        ;;
    ara)
        echo "[AR]"
        ;;
    *)
        echo "$layout"
        echo "$layout"
        ;;
esac

