#!/bin/bash

color="#7aa2f7"

mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')

mem_used=$((mem_total - mem_available))

mem_percent=$((mem_used * 100 / mem_total))

echo "<span foreground='$color'>Ram</span> ${mem_percent}%"

