#!/bin/bash

volume=$(amixer get Master | grep -oP '\[\d+%\]' | head -1 | tr -d '[]')
mute=$(amixer get Master | grep -oP '\[(on|off)\]' | head -1 | tr -d '[]')

if [ "$mute" = "off" ]; then
    echo "MUTED"
else
    echo "<span color='#e0c989'>󰕾 </span>$volume"
fi

