#!/bin/bash

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1)
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -oP '(yes|no)')

if [[ $mute == "yes" ]]; then
    echo "off"
else
    echo "$volume"
fi
