#!/bin/bash

color="#7aa2f7"

wifi_iface=$(iw dev | awk '$1=="Interface"{print $2}' | head -n1)

if [[ -z "$wifi_iface" ]]; then
    echo "<span foreground='$color'>Wifi</span> down"
    exit 0
fi

state=$(cat /sys/class/net/"$wifi_iface"/operstate 2>/dev/null)

if [[ "$state" == "up" ]]; then
    echo "<span foreground='$color'>Wifi</span> up"
else
    echo "<span foreground='$color'>Wifi</span> down"
fi

