#!/bin/bash

wifi_iface=$(iw dev | awk '$1=="Interface"{print $2}' | head -n1)

if [[ -z "$wifi_iface" ]]; then
    echo "down"
    exit 0
fi

state=$(cat /sys/class/net/"$wifi_iface"/operstate 2>/dev/null)

if [[ "$state" == "up" ]]; then
    signal=$(grep "$wifi_iface" /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "<span color='#e5c07b'>󰤨 </span>${signal}%"
else
    echo "<span color='#e5c07b'>󰤨 </span>off"
fi

